DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS token;

CREATE TABLE user (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  username TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL
);

CREATE TABLE token (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  tokenstr TEXT UNIQUE NOT NULL,
  rootId INTEGER,
  refreshed BOOLEAN
);